// <auto-generated />
using System;
using FixItNow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FixItNow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313192350_SeedInitialUsers")]
    partial class SeedInitialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FixItNow.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FixItNow.Api.Models.RepairRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetWorkerIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepairRequests");
                });

            modelBuilder.Entity("FixItNow.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("FixItNow.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Nguyễn Văn A",
                            PasswordHash = "123456",
                            Phone = "0900000001",
                            Role = 1,
                            WorkerProfileId = 101
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Trần Thị B",
                            PasswordHash = "123456",
                            Phone = "0900000002",
                            Role = 1,
                            WorkerProfileId = 102
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Phạm C",
                            PasswordHash = "123456",
                            Phone = "0900000003",
                            Role = 1,
                            WorkerProfileId = 103
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Lê Văn D",
                            PasswordHash = "123456",
                            Phone = "0900000004",
                            Role = 1,
                            WorkerProfileId = 104
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Phạm Văn E",
                            PasswordHash = "123456",
                            Phone = "0900000005",
                            Role = 1,
                            WorkerProfileId = 105
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Một",
                            PasswordHash = "123456",
                            Phone = "0900000006",
                            Role = 0
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Hai",
                            PasswordHash = "123456",
                            Phone = "0900000007",
                            Role = 0
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Ba",
                            PasswordHash = "123456",
                            Phone = "0900000008",
                            Role = 0
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Bốn",
                            PasswordHash = "123456",
                            Phone = "0900000009",
                            Role = 0
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "",
                            FullName = "Khách Hàng Năm",
                            PasswordHash = "123456",
                            Phone = "0900000010",
                            Role = 0
                        });
                });

            modelBuilder.Entity("FixItNow.Api.Models.WorkerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOrStore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkerProfiles");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "123 Lê Lợi, Quận 1",
                            Description = "Sửa điện nhanh chóng, an toàn",
                            Location = "Hồ Chí Minh",
                            NameOrStore = "Thợ Điện Nguyễn Văn A",
                            PhoneNumber = "0900000001",
                            Rating = 4.7999999999999998,
                            Services = "Sửa điện,Máy lạnh"
                        },
                        new
                        {
                            Id = 102,
                            Address = "456 Trần Hưng Đạo, Hoàn Kiếm",
                            Description = "Chuyên sửa ống nước, vòi sen",
                            Location = "Hà Nội",
                            NameOrStore = "Trần Thị B Dịch Vụ Nước",
                            PhoneNumber = "0900000002",
                            Rating = 4.5,
                            Services = "Sửa nước"
                        },
                        new
                        {
                            Id = 103,
                            Address = "789 Nguyễn Văn Linh, Hải Châu",
                            Description = "Thay lốc tủ lạnh, kiểm tra tivi",
                            Location = "Đà Nẵng",
                            NameOrStore = "Cửa hàng Sửa Chữa C",
                            PhoneNumber = "0900000003",
                            Rating = 5.0,
                            Services = "Điện gia dụng,Máy lạnh"
                        },
                        new
                        {
                            Id = 104,
                            Address = "101 Lý Tự Trọng, Ninh Kiều",
                            Description = "Nhận sửa mọi thứ trong nhà",
                            Location = "Cần Thơ",
                            NameOrStore = "Lê Văn D - Đa năng",
                            PhoneNumber = "0900000004",
                            Rating = 4.2000000000000002,
                            Services = "Sửa điện,Sửa nước,Điện gia dụng"
                        },
                        new
                        {
                            Id = 105,
                            Address = "202 Đồng Khởi, Biên Hòa",
                            Description = "Chuyên sửa cửa gỗ, tủ gỗ",
                            Location = "Đồng Nai",
                            NameOrStore = "Phạm Văn E Mộc",
                            PhoneNumber = "0900000005",
                            Rating = 4.7000000000000002,
                            Services = "Khác"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
